version: "3"
services:
    database:
        image: postgres:alpine
        env_file:
            - db.env
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
    main-server:
        build: ./
        command: npx nodemon --legacy-watch --exec "node --inspect-brk=0.0.0.0:9229 ./src/index.js"
        ports:
            - 8080:8080
            - 9229:9229
        volumes:
            - .:/user/src/app
            - node_modules:/usr/src/app/node_modules
        depends_on:
            - database
        env_file:
            - db.env
            - main-server.env
        environment:
            NODE_ENV: development
volumes:
    node_modules:
    postgres:
